title: Alen Jose
logo: /assets/passport_size_photo.jpg
description: |
  <style>
    img[src*="passport_size_photo.jpg"] {
      width: 50%; /* Reduces size */
      height: auto;
      border-radius: 50%; /* Makes image round */
      display: block;
      margin: 0 auto;
    }
  </style>
#description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
