title: Alen Jose
logo: /assets/passport_size_photo.png
description: |
  <style>
    img[src*="passport_size_photo.png"] {
      width: 50%; /* Reduces size */
      height: auto;
      # border-radius: 50%; /* Makes image round */
      display: block;
      margin: 0;
      float: left;
    }
    /* Hide the "View my GitHub" link */
    a[href*="github.com"] {
      display: none;
    }
  </style>
theme: jekyll-theme-minimal
